version: '3.8'

services:
  db_order:
    image: postgres:16
    environment:
      POSTGRES_DB: order_db_test
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: test_123
    volumes:
      - pgdata_order_test:/var/lib/postgresql/data

  db_customer:
    image: postgres:16
    environment:
      POSTGRES_DB: customer_db_test
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: test_123
    volumes:
      - pgdata_customer_test:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order_service:
    build: ./order_service
    environment:
      RAILS_ENV: test
      DB_HOSTNAME: db_order
      DB_NAME: order_db_test
      DB_USERNAME: user_db
      DB_PASSWORD: test_123
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      CUSTOMER_SERVICE_URL: http://customer_service:3000
    depends_on:
      - db_order
      - rabbitmq
    volumes:
      - ./order_service:/app
      - ./order_service/config/master.key:/app/config/master.key

  customer_service:
    build: ./customer_service
    environment:
      RAILS_ENV: test
      DB_HOSTNAME: db_customer
      DB_NAME: customer_db_test
      DB_USERNAME: user_db
      DB_PASSWORD: test_123
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db_customer
      - rabbitmq
    volumes:
      - ./customer_service:/app
      - ./customer_service/config/master.key:/app/config/master.key

volumes:
  pgdata_order_test:
  pgdata_customer_test:
