default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOSTNAME", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_production") %>
